spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties..javax.persistence.validation.mode=none

https://chrome.google.com/webstore/detail/jsonview/gmegofmjomhknnokphhckolhcffdaihd
#debug=true
#trace=true
logging.level.root=INFO
#logging.level.com.eazybytes.eazyschool.aspects=ERROR
#logging.level.com.eazybytes.eazyschool.controller=TRACE

logging.group.eazyschool_error=com.eazybytes.eazyschool.aspects,com.eazybytes.eazyschool.controller
logging.level.eazyschool_error=ERROR
spring.output.ansi.enabled=always
